#!/usr/bin/env python3
"""Generate the regression fixtures from an installed spicedmodel wheel.

Run this script from outside the source tree, using the Python interpreter in
the virtual environment into which the freshly built wheel was installed.
Golden files are deliberately not regenerated by the test suite.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import importlib
import io
import json
from pathlib import Path
import subprocess

import numpy as np
import spicedmodel


R_MAX = np.nextafter(np.float32(5.9), np.float32(-np.inf))
RADIUS = np.linspace(np.float32(2.0), R_MAX, 9, dtype=np.float32)
MLT = np.linspace(0.0, 24.0, 12, endpoint=False, dtype=np.float32)
SMR = np.array([-100.0, -70.0, -30.0, 0.0, 30.0], dtype=np.float32)
F107 = np.array([70.0, 100.0, 150.0, 200.0], dtype=np.float32)
FOURIER_M = tuple(range(1, 7))

MODEL_SPECS = {
    "Mav": ("SMR", SMR),
    "MavHot": ("F107", F107),
    "MavPS": ("SMR", SMR),
    "MavPT": ("SMR", SMR),
    "Prob": ("SMR", SMR),
    "PS": ("SMR", SMR),
    "PT": ("SMR", SMR),
    "Density": ("SMR", SMR),
    "PMD": ("SMR", SMR),
}


def _git(repository: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repository), *args],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def _library_hashes() -> dict[str, str]:
    package = Path(spicedmodel.__file__).resolve().parent
    libraries = package.joinpath("__data", "spiced", "lib")
    result = {}
    for path in sorted(libraries.rglob("libspiced.*")) + sorted(
        libraries.rglob("libann.*")
    ):
        if path.suffix in {".so", ".dylib", ".dll"}:
            result[str(path.relative_to(package))] = hashlib.sha256(
                path.read_bytes()
            ).hexdigest()
    return result


def _evaluate(model, parameter: str, values: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    mlt, radius = np.meshgrid(MLT, RADIUS)
    average = np.asarray(model(mlt, radius, Coord="ml"), dtype=np.float32)
    scaled = np.stack(
        [model(mlt, radius, Coord="ml", **{parameter: float(value)}) for value in values]
    ).astype(np.float32)
    return average, scaled


def _evaluate_components(
    model, parameter: str, values: np.ndarray
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Return isolated DC and m=1..6 terms for average and scaled models."""
    mlt, radius = np.meshgrid(MLT, RADIUS)

    average_dc = np.asarray(
        model(mlt, radius, Coord="ml", OnlyDC=True), dtype=np.float32
    )
    average_fourier = np.stack(
        [
            model(mlt, radius, Coord="ml", ShowDC=False, m=[m, m])
            for m in FOURIER_M
        ]
    ).astype(np.float32)

    scaled_dc = np.stack(
        [
            model(
                mlt,
                radius,
                Coord="ml",
                OnlyDC=True,
                **{parameter: float(value)},
            )
            for value in values
        ]
    ).astype(np.float32)
    scaled_fourier = np.stack(
        [
            np.stack(
                [
                    model(
                        mlt,
                        radius,
                        Coord="ml",
                        ShowDC=False,
                        m=[m, m],
                        **{parameter: float(value)},
                    )
                    for m in FOURIER_M
                ]
            )
            for value in values
        ]
    ).astype(np.float32)
    return average_dc, average_fourier, scaled_dc, scaled_fourier


def _json_values(array: np.ndarray) -> list[float | None]:
    return [float(value) if np.isfinite(value) else None for value in array.ravel()]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent / "data",
        help="fixture output directory",
    )
    parser.add_argument(
        "--repository",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="repository used only to record commit provenance",
    )
    args = parser.parse_args()

    repository = args.repository.resolve()
    installed_package = Path(spicedmodel.__file__).resolve()
    source_package = repository / "spicedmodel"
    if installed_package.is_relative_to(source_package):
        raise SystemExit(
            "Refusing to generate fixtures from the source tree. Build a wheel, "
            "install it into a virtual environment, and run this script from a "
            "separate working directory."
        )

    args.output.mkdir(parents=True, exist_ok=True)
    metadata = {
        "schema_version": 2,
        "package_version": spicedmodel.__version__,
        "package_commit": _git(repository, "rev-parse", "HEAD"),
        "spiced_commit": _git(
            repository / "spicedmodel" / "__data" / "spiced", "rev-parse", "HEAD"
        ),
        "library_sha256": _library_hashes(),
    }

    for name, (parameter, parameter_values) in MODEL_SPECS.items():
        model = getattr(importlib.import_module("spicedmodel"), name)
        average, scaled = _evaluate(model, parameter, parameter_values)
        average_dc, average_fourier, scaled_dc, scaled_fourier = _evaluate_components(
            model, parameter, parameter_values
        )
        document = {
            **metadata,
            "model": name,
            "inputs": {
                "coord": "ml",
                "radius_nominal_limits": [2.0, 5.9],
                "radius": RADIUS.tolist(),
                "mlt": MLT.tolist(),
                "fourier_m": list(FOURIER_M),
                parameter: parameter_values.tolist(),
            },
            "average": {"shape": list(average.shape), "values": _json_values(average)},
            "scaled": {"shape": list(scaled.shape), "values": _json_values(scaled)},
            "components": {
                "average": {
                    "dc": {
                        "shape": list(average_dc.shape),
                        "values": _json_values(average_dc),
                    },
                    "fourier": {
                        "shape": list(average_fourier.shape),
                        "values": _json_values(average_fourier),
                    },
                },
                "scaled": {
                    "dc": {
                        "shape": list(scaled_dc.shape),
                        "values": _json_values(scaled_dc),
                    },
                    "fourier": {
                        "shape": list(scaled_fourier.shape),
                        "values": _json_values(scaled_fourier),
                    },
                },
            },
        }
        destination = args.output / f"{name.lower()}.json.gz"
        with destination.open("wb") as raw_stream:
            with gzip.GzipFile(fileobj=raw_stream, mode="wb", mtime=0) as compressed:
                with io.TextIOWrapper(compressed, encoding="utf-8", newline="\n") as stream:
                    json.dump(
                        document,
                        stream,
                        allow_nan=False,
                        separators=(",", ":"),
                        sort_keys=True,
                    )
                    stream.write("\n")
        print(destination)


if __name__ == "__main__":
    main()
